#Configure database connection information - Four elements
spring:
  datasource:
    #Driver class name
    driver-class-name: com.mysql.cj.jdbc.Driver
    #The url of the database connection (note that it is followed by a single slash)
    url: jdbc:mysql://192.168.222.128:3306/mybatis
    #User name for connecting to the database
    username: Amicus
    #Password for connecting to the database
    password: w1371821736
  servlet:
    multipart:
      #Configure the limit on the upload size of a single file
      max-file-size: 10MB
      #Configure the maximum size limit for a single request (multiple files can be uploaded in one request)
      max-request-size: 100MB

#Configuration of Mybatis
mybatis:
  configuration:
    #Configure the location of mybatis output log, output console
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #Open the controller of mybatis auto named mapping
    map-underscore-to-camel-case: true

#User-defined configuration of OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tEuitKkCe9WuDyUDU76
    accessKeySecret: qPdfE8HGV0AOBWEErDL7r2ZVH4LNMd
    bucketName: anthony-brown

#spring controller logging of transaction
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
